### PR TITLE
Fix issues with Installer (v0.2.0)

### LINKED ISSUE #4: allow to install releases (not only branches)
Up to now, you can only chose a branch on github to install; it would be good to be able to also install releases by giving their version number.  
The problem is that releases have a different folder structure (./Assets/com.edia.xxx   vs ./com.edia.xxx).    
We should check for the form of the entry and if it matches SemVer import from the according folder .

### LINKED ISSUE #7: add EDIA RCAS
add EDIA RCAS to installer

### PR DESCRIPTION
**Pull request by eioe**
- add RCAS (fixes #7 )
- allow to load EDIA modules both from branches and releases  (fixes #4 )
- fix visualization issues with version and source
- release new package (v0.2.0)

### CODE REVIEW

File: Assets/Editor/EdiaInstaller.cs [hunk 1]
```diff
@@ -3,725 +3,726 @@
...
+                _statusMessage = "Error starting install. See Console.";
+                _isInstallingEdia = false;
+
+                ClearState();
+            }
+
+            GetWindowIfOpen()?.Repaint();
+        }
+
+        private static void PackageProgress() {
```
Comment (thefirstfloor) [inline Assets/Editor/EdiaInstaller.cs:648]: `PackageProgress` sounds to me like "done", or "34%", iow: a state, not a method.
Maybe name it `HandlePackageProgress` or something simular

Comment (thefirstfloor) [inline Assets/Editor/EdiaInstaller.cs:648]:
```suggestion
        private static void HandlePackageProgress() {
```

Comment (eioe) [reply Assets/Editor/EdiaInstaller.cs:648]: thx. I'll implement when making a new release.

Comment (eioe) [reply Assets/Editor/EdiaInstaller.cs:648]: thx. I'll implement when making a new release.

**Comment by eioe** [comment]
Did you test it? Maybe in some real project (i.e., the one where it threw namespace conflicts? was that `tidal`? )? 
Just curious, not saying you should. (I could / have obv do that myself. Not with tidal though.)

**Comment by thefirstfloor** [comment]
No, did not test it. I did a 'felix', iow: looked at the code online on github :)

**Comment by eioe** [comment]
haha, classic Felix, yes. Then let's battle test it.
